---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
  checks:
    newline-per-chained-call:
      enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.module"
exclude_paths:
- node_modules/
- "jasmine/lib/jasmine-2.3.4/jasmine.js"
- "jasmine/lib/jasmine-2.3.4/jasmine-html.js"
- "src/app.js"
