engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- node_modules/
- "jasmine/lib/jasmine-2.3.4/jasmine.js"
- "jasmine/lib/jasmine-2.3.4/jasmine-html.js"
